//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlygiaonhanhang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.PhanCongVCs = new HashSet<PhanCongVC>();
        }
    
        public int Id { get; set; }
        public string TenKH { get; set; }
        public Nullable<int> KhuVuc { get; set; }
        public string SDT { get; set; }
        public string TenMH { get; set; }
        public Nullable<int> SoKG { get; set; }
        public Nullable<int> IdDV { get; set; }
        public Nullable<double> PhiVC { get; set; }
        public Nullable<int> TinhTrang { get; set; }
        public string DiaChi { get; set; }
    
        public virtual DiaDiem DiaDiem { get; set; }
        public virtual DichVu DichVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanCongVC> PhanCongVCs { get; set; }
    }
}
