//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlygiaonhanhang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanCongVC
    {
        public int Id { get; set; }
        public string HoTenTX { get; set; }
        public string BKS { get; set; }
        public Nullable<int> IdDH { get; set; }
        public Nullable<int> IdNV { get; set; }
        public string SDT { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
